version: "2.1"

volumes:
  app:
    driver: local
  db:
    driver: local
  results:
    driver: local

services:
  results:
    container_name: mayan-edms-results
    image: healthcheck/redis
    volumes:
      - results:/data
  db:
    container_name: mayan-edms-postgres
    image: postgres:9.5
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayanuserpass
      POSTGRES_USER: mayan
    volumes:
      - db:/datadrive/mayan-edms/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  mayan-edms:
    container_name: mayan-edms
    image: mayanedms/mayanedms:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayanuserpass
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_CONN_MAX_AGE: 60
      LETSENCRYPT_HOST: sdocs.alpineanimalhospitalcda.com
      LETSENCRYPT_EMAIL: jeff.s.bailey@gmail.com
      VIRTUAL_HOST: sdocs.alpineanimalhospitalcda.com
      VIRTUAL_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - app:/datadrive/mayan-edms/media

  nginx:
      restart: always
      image: nginx
      container_name: nginx
      labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "/etc/nginx/conf.d"
        - "/etc/nginx/vhost.d"
        - "/usr/share/nginx/html"
        - "./certs:/etc/nginx/certs:ro"

  docker-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: docker-gen
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/root/docker/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
      - NGINX_PROXY_CONTAINER=nginx
