version: "2"

services:
  db:
    restart: always
    container_name: mayan-edms-postgres
    image: postgres:9.5
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayanuserpass
      POSTGRES_USER: mayan
    volumes:
      - /datadrive/mayan-edms/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - back-tier
  mayan-edms:
    restart: always
    depends_on: 
    - db
    container_name: mayan-edms
    image: mayanedms/mayanedms:latest
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayanuserpass
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_CONN_MAX_AGE: 60
      LETSENCRYPT_HOST: sdocs.alpineanimalhospitalcda.com
      LETSENCRYPT_EMAIL: jeff.s.bailey@gmail.com
      VIRTUAL_HOST: sdocs.alpineanimalhospitalcda.com
      VIRTUAL_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - /datadrive/mayan-edms/media:/var/lib/mayan
    networks:
      - proxy-tier
      - back-tier
  nginx-proxy:                                                      
    image: jwilder/nginx-proxy                                      
    ports:                                                          
      - "80:80"                                                     
      - "443:443"           
    depends_on: 
      - mayan-edms                                        
    volumes:                                                        
      - "/etc/nginx/vhost.d"                                        
      - "/usr/share/nginx/html"                                     
      - "/var/run/docker.sock:/tmp/docker.sock:ro"                  
      - "~/certs:/etc/nginx/certs"      
    networks:
      - proxy-tier                            
                                                                    
  letsencrypt-nginx-proxy-companion:                                
    image: jrcs/letsencrypt-nginx-proxy-companion                   
    volumes:                                                        
      - "/var/run/docker.sock:/var/run/docker.sock:ro"              
    volumes_from:                                                   
      - "nginx-proxy"                                               

networks:
  proxy-tier:
  back-tier:
