version: '2.1'                                                                                        
                                                                                                      
volumes:                                                                                              
    app:                                                                                              
        driver: local                                                                                 
    db:                                                                                               
        driver: local                                                                                 
    results:                                                                                          
        driver: local                                                                                 
                                                                                                      
services:                                                                                             
  results:                                                                                            
    container_name: mayan-edms-results                                                                
    image: healthcheck/redis                                                                          
    volumes:                                                                                          
      - results:/data                                                                                 
  db:                                                                                                 
    container_name: mayan-edms-postgres                                                               
    image: postgres:9.5                                                                               
    environment:                                                                                      
      POSTGRES_DB: mayan                                                                              
      POSTGRES_PASSWORD: mayanuserpass333                                                             
      POSTGRES_USER: mayan                                                                            
    volumes:                                                                                          
      - db:/datadrive/mayan-edms/postgres                                                             
    ports:                                                                                            
      - "5432:5432"                                                                                   
    healthcheck:                                                                                      
      test: ["CMD-SHELL", "pg_isready -U postgres"]                                                   
      interval: 10s                                                                                   
      timeout: 5s                                                                                     
      retries: 5                                                                                      
  mayan-edms:                                                                                         
    container_name: mayan-edms                                                                        
    image: mayanedms/mayanedms:latest                                                                 
    depends_on:                                                                                       
      db:                                                                                             
        condition: service_healthy                                                                    
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayanuserpass333
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_CONN_MAX_AGE: 60
    ports:
      - "80:8000"
    volumes:
      - app:/datadrive/mayan-edms/media